# Generated by Django 5.2 on 2025-08-25 12:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_alter_run_athlete'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('goals', models.TextField(default=None, max_length=1500, null=True, verbose_name='Коротко о себе')),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(900)], verbose_name='Вес')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
