# Generated by Django 5.2 on 2025-08-25 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(899), django.core.validators.MinValueValidator(1)], verbose_name='Вес'),
        ),
    ]
