# Generated by Django 5.2 on 2025-09-25 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_run_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название артефакта')),
                ('uid', models.CharField(max_length=100, unique=True, verbose_name='Уникальный идентификатор')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('picture', models.URLField(verbose_name='Ссылка на изображение')),
                ('value', models.IntegerField(verbose_name='Крутизна артефакта')),
            ],
            options={
                'verbose_name': 'Коллекционный артефакт',
                'verbose_name_plural': 'Коллекционные артефакты',
            },
        ),
        migrations.AlterModelOptions(
            name='athleteinfo',
            options={'verbose_name': 'Информация об атлете', 'verbose_name_plural': 'Информация об атлетах'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'verbose_name': 'Забег', 'verbose_name_plural': 'Забеги'},
        ),
    ]
