# Generated by Django 5.2 on 2025-10-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
