# Generated by Django 5.2 on 2025-12-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0015_run_speed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribeToCoach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подписки"
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions_as_athlete",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Атлет",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers_as_coach",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на тренеров",
                "verbose_name_plural": "Подписки на тренеров",
                "unique_together": {("athlete", "coach")},
            },
        ),
    ]
