# Generated by Django 5.2 on 2025-12-30 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0016_subscribetocoach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubscribeToCoach",
            new_name="Subscribe",
        ),
    ]
