# Generated by Django 5.2 on 2026-02-22 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0017_rename_subscribetocoach_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribe",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг тренера",
            ),
        ),
    ]
